name: Lint and Format Code

on: [push, pull_request]

jobs:
  lint-and-format:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.1'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black

    - name: Lint with Flake8
      run: flake8 .

    - name: Format code with Black
      run: black .

    - name: Commit and Push Changes
      run: |
        git config --global user.name 'lordyabu'
        git config --global user.email 'ay13@illinois.edu'
        git add .
        git commit -m "Apply Black Formatting" -a || echo "No changes to commit"
        git push
