name: Run Unit Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        python -m pytest --exitfirst src/envs/stock/graph_unittests.py
        python -m pytest --exitfirst src/envs/stock/trader_unittests.py

    - name: Check for test failures
      run: |
        if [ -f pytest.failures ]; then
          echo "Test failures detected."
          exit 1
        fi