name: Run Unit Tests

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  test:
    runs-on: windows-latest  # Use a Windows runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.13  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have a requirements file

    - name: Run unit tests
      run: |
        python -m pytest src/envs/stock/graph_unittests.py
        python -m pytest src/envs/stock/trader_unittests.py
